### ISSUE TITLE
Semantic Interpretation

### ISSUE THREAD

**Issue by mikeday** [yeslogic/fathom#166]
Binary types allow us to understand formats syntactically in the form of:

 - primitive integers
 - structs and fields
 - arrays
 - unions

But formats also have semantic interpretations, starting with abstract data structures like sets, functions, maps, or relations.

For example, the table index in OpenType is syntactically an array of structs, but semantically it makes sense to interpret it as a partial function or map from table tags to tables. Similarly the Coverage and ClassDef structs in the OpenType layout tables can be encoded syntactically in several different forms, all of which can be interpreted semantically as sets of glyph indices.

There is also the semantic domain of text strings, for example interpreting a 7-bit integer as an ASCII character, or going from a byte array to UTF-8 encoded codepoints to a Unicode string.

Beyond this the sky is the limit: the semantic domain of 2D images and paths, the time domain for movies and audio, and so on.

**Comment by brendanzab** [comment]
Yeah, this would be super interesting! This could be useful for a file browser - instead of a simple tree view, it'd be nice if you could swap between semantic interpretations on the nodes. Kind of like how in [TreeSheets](http://strlen.com/treesheets/) you can swap between semantic interpretations of nodes:

![](strlen.com/treesheets/docs/images/screenshots/screenshot_todo_half.png)

**Comment by brendanzab** [comment]
I guess I'm not sure what this would look like from the type system's perspective. Do we need some way of attaching this kind of metadata to 'parts' of a term?

**Comment by brendanzab** [comment]
The idea of annotating terms kind of reminds me of some of the stuff we’ll need to do for different back ends. I can kind of imagine there being some ‘path’ syntax for pointing to specific bits of a term and you could merge those into a term. This could be used for adding documentation, or rewriting identifiers for different backends.

So say you have this:

```
User = struct {
    name : Array 32 U8,
};
```

Perhaps you could have a ‘hints’ file:

```
User.term.interpretations = [ Struct, Table ];
User.term.doc_string = "A user record.";
User.term.nominal_name = "User";
User.term.fields["name"].interpretations = [ Bytes, Ascii ];
User.term.fields["name].doc_string = "The name of the user.";
```

And perhaps you could have a way of adding these hints inline too for defaults, like how you can have annotations in Rust. 🤔
