### ISSUE TITLE
Simple DDL compilation strategy for Rust

### ISSUE THREAD

**Issue by mikeday** [yeslogic/fathom#190]
To compile the DDL to Rust we need a compilation strategy that is _complete_ in that it can handle every binary format type, _simple_ in that it is easy to implement, and _usable_ in that it presents a reasonable interface to Rust code that wishes to call it. Here is one possibility based on our experimentation with hand-written parsing code in the Allsorts implementation.

Primitive Types
============

Primitive binary types map directly to the appropriate Rust type:
```
host(U8) = u8
host(U16Be) = u16
host(U16Le) = u16
host(U32Be) = u32
host(U32Le) = u32
```

If Types
=======

Rust does not support type-level conditional expressions so they are mapped to an enum that represents both possible branches, checked at runtime:
```
host(if _Cond then Type1 else Type2) = Either<host(Type1), host(Type2)>
```

Match Types
==========

Match expressions can be desugared to nested if expressions but these will map to nested enums that are awkward to use and inefficient to store. A better approach is to map each match expression to a custom enum type as in this example:
```
host(match _Expr with _Val1 => Type1, _Val2 => Type2, otherwise Type3) = CustomEnum

enum CustomEnum {
    Branch0(host(Type1)),
    Branch1(host(Type2)),
    Branch2(host(Type3)),
}
```
We could extend this compilation scheme with directives to specify suitable names for the custom enum type and its branches to improve the readability of the generated API.

Array Types
==========

Arrays map to Vecs where the length is tracked at runtime and passed as an argument when parsing:
```
host(Array(_Len, Type)) = Vec<host(Type)>
  where ReadBinary<Vec<T>> has Args: usize
```

Function Types
============

```
double : int -> int = \n . n + n

smart_int : bool -> Format = \b . if b then U16Be else U32Be

if_then_else : bool -> Format -> Format -> Format = \b . \t1 . \t2 . if b then t1 else t2

octet : Format -> Format = \t . Array 8 t

wut : (Format -> Format) -> bool -> Format = \f . \b . if b then f U16Be else f U32Be

wut2 : (Format -> Format) -> bool -> Format -> Format = \f . \b . \t . if b then f t else f (f t)
```

```
// double is erased as it does not return a type

// argument is erased, result is a type
type SmartInt = Either<u16, u32>;

trait TypeFunc<T> {
    type ResultType;
}

type TypeCall<S, T> = <S as TypeFunc<T>>::ResultType;

enum Octet {}

impl<T> TypeFunc<T> for Octet {
    type ResultType = Vec<T>;
}

enum IfThenElse {}

impl<S, T> TypeFunc<(S, T)> for IfThenElse {
    type ResultType = Either<S, T>;
}

struct Wut<F>(Either<TypeCall<F, u16>, TypeCall<F, u32>>)
    where F: TypeFunc<u16> + TypeFunc<u32>;

struct Wut2<F>(PhantomData<F>);

impl<F, T> TypeFunc<T> for Wut2<F> where F: TypeFunc<T> + TypeFunc<TypeCall<F, T>> {
    type ResultType = Either<TypeCall<F, T>, TypeCall<F, TypeCall<F, T>>>;
}
```

Structs
======

Binary structs map to Rust structs:
```
host(struct Name { Fields }) = struct Name { host(Fields) }
```

Structs: Format Parameters
======================

For binary structs that are parameterised by another binary format we can preserve the type parameter in the Rust definition:
```
host((TypeArg: FormatKind) -> struct Name { Fields }) =
  struct Name<TypeArg> { host(Fields) }
```
Here is a concrete example of how that would work in practice:
```
struct Foo (ItemType: Format) {
    len: U16Be,
    items: Array len ItemType,
}

struct Foo<ItemType> {
    len: u16,
    items: Vec<ItemType>,
}
```

Structs: Value Parameters
=====================

For binary structs that are parameterised by a host value we cannot express the dependency in Rust, so we erase it from the type and pass it in explicitly as an argument when parsing:
```
host((x: HostType) -> struct Name { Fields }) =
  struct Name { x: HostType, host(Fields) }
  where ReadBinary trait has Args: HostType
```

Here is a concrete example of how that would work in practice:
```
struct Foo (len: uint) {
    data: Array len U16Be,
}

// ReadBinary trait for Foo has Args: usize
struct Foo {
    len: usize,
    data: Vec<u16>,
}
```

Structs: Host Function Parameters
===========================

For binary structs that are parameterised by functions over host types we can also erase these from the Rust type:
```
struct Foo (f : uint -> uint) {
    len: U16Be,
    data: Array (f len) U16Be,
}

struct Foo {
    len: usize,
    data: Vec<u16>,
}
```
Erasing these function parameters is safe as a host function cannot affect the final type as this compilation strategy ignores array lengths and if/match conditions.

Structs: Format Function Parameters
=============================

For binary structs that are parameterised by functions that return binary formats we can preserve the type parameter in Rust and represent each function as a type that implements a trait with an associated type that is the host type of the function result. Here is some sample DDL:
```
struct Foo (f: uint -> Format) {
    tag: U16Be,
    data: f tag,
}

sample_func : uint -> Format = \x . if x = 0 then U16Be else U32Be

Bar = Foo sample_func
```
And here is how it could be compiled to Rust:
```
struct Foo<T: FormatFunc> {
    tag: u16,
    data: T::ResultType,
}

enum SampleFunc;

impl FormatFunc for SampleFunc {
    type ResultType = Either<u16, u32>;
}

type Bar = Foo<SampleFunc>;
```
Unfortunately this approach does not work for format constructors like this: (FIXME actually it does, it's fine!)
```
struct Foo (f: Format -> Format) {
    wut: f U16Be
}

octet : Format -> Format = \t . Array 8 t

Bar = Foo octet
```
Attempting to compile this in the same way runs into the problem that now the function type needs to be parametric on its type argument, which Rust cannot express. This may require parameterising the Rust struct for _each invocation_ of the type-level function within it. (FIXME no, it doesn't!)

Other Functions
=============

If the DDL allows defining binary format type families that aren't based on structs we can treat them as if they were structs with one field and map them to a tuple struct. Here is an example of a type dependency:
```
UnusedArg = \T: Format, U16Be

struct UnusedArg<T>(u16);
```

Here is an example of a value dependency:
```
FlexibleU16Be = \x: bool, if x then U16Be else U16Le

// ReadBinary trait for FlexibleU16Be has Args: bool
struct FlexibleU16Be(Either<u16, u16>);
```

And finally a dependency on types and values:
```
ByteOrSomething = \x: bool, \T: Format, if x then U8 else T

// ReadBinary trait for ByteOrSomething has Args: bool
struct ByteOrSomething<T>(Either<u8, T>);    
```

Offsets
======

The simplest way to handle offsets is mapping them to reference counted pointers to cached objects, so that multiple offsets to the same location will only be parsed once and will not incur any memory usage overhead.
```
host(Offset(T)) => Rc<host(T)>
```

Potential Improvements
===================

Small arrays of constant size could be mapped to Rust arrays rather than Vecs:
```
host(Array(Len, Type)) = [host(Type); Len] where Len * sizeof(Type) <= 32
```

Conditional expressions where both branches have the same Rust type could be simplified so that `Either<T, T>` is replaced with `T`, for example in these situations:
```
host(if BigEndian then U16Be else U16Le) = Either<u16, u16> = u16

host(if Small then Array 4 U8 else Array 8 U8) = Either<Vec<u8>, Vec<u8>> = Vec<u8>
```
(In general no information is lost as the condition will still be available elsewhere, but in some cases it might be more convenient to keep the enum).

Some parametric structs could be inlined and specialised for convenience and/or efficiency. The simplest way to support this would be to make the author explicitly request it. For example:
```
Foo = \x: bool, if x then U16Be else U32Be
Bar = Foo true
Meep = Foo true // directive to inline and specialise this

struct Foo(Either<u16, u32>);
struct Bar(Foo);
struct Meep(u16);
```

**Comment by brendanzab** [comment]
Nice, this is a pretty great run-through!

**Comment by mikeday** [comment]
I've updated this compilation scheme to include match types.

**Comment by mikeday** [comment]
Now updated to include structs parameterised by functions, which works fine for Int -> Format but unfortunately Format -> Format will require jumping through some more hoops I think.

**Comment by brendanzab** [comment]
One thing we also need to consider is the compilation of the reader. For example, with `if` types we'll need to store the perform the conditional expression somewhere. This is what is currently causing my type-level if branch to fail to compile. (see https://github.com/yeslogic/ddl/commit/9020b8d16d5553b960ae18e5c8c22babb2df52e2)

**Comment by brendanzab** [comment]
Got some resources for compiling languages like the DDL to 'simpler' type systems like Rust's:

> **brendanzab**: Does anyone know of any examples of a compiler that takes a dependent type system and compiles it to a language where terms and types are separate? For context, I'm making a dependently typed binary data description language (a variation of MLTT, extended with format descriptions), and the target language that I'm focusing on for now is Rust. I'm ok with having errors in the compiler if something can't be translated nicely, but I'd like to produce a reasonably ok result at the end that can be audited reasonably.
>
> I guess I just see lots of examples of 'erasing' types, but I want to preserve types, but split them into a separate 'level' and erase kinds.
>
> Atm I'm thinking I'll make a separate pass for 'stratifying' (not sure of a better word) the language into terms, types, and kinds, with 'lifted' terms and types. Then I'll erase the kinds in another pass.

> **cwjnkins**: Sounds a bit like dependent interoperability (https://hal.inria.fr/hal-01629909v2/document) or type theory in color https://dl.acm.org/doi/pdf/10.1145/2544174.2500577?download=true. Also related might be this paper by Paulin-Mohring on extracting F-omega terms from CC: https://dl.acm.org/doi/pdf/10.1145/75277.75285

**Comment by brendanzab** [comment]
Here's an interesting Bachelor's Thesis: [Compiling Agda to System Fω in Theory](https://www.cl.cam.ac.uk/~mpf23/papers/Types/SystemFi.pdf)
