### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by mikeday** [yeslogic/fathom#239]
Some thoughts for a future `fathom-cli` package that uses the DDL interpreter to provide what is essentially a supercharged version of the `file` command and/or the equivalent of `grep` for binary files. :nerd_face:

## Syntax
```
fathom
  [--format=NAME | --format-file=FILE]
  [--summary | --dump | --query=QUERY | --query-file=FILE ]
  FILES...
```

## Format Options

**--format**=*NAME* is an optional argument for specifying the name of the format description in the installed catalog, for example "opentype", that will be used to process the files.

**--format-file**=*FILE* is an optional argument for specifying the file containing the format description, for example "path/to/myformat.ddl", that will be used to process the files.

If neither format option is provided the files will be processed after best-effort identification using the installed catalog of format descriptions.

## Output Options

**--summary** prints a brief summary of each file based on the format description. This may include printing the type or version or other important details about the file but may not validate the entire file contents.

**--dump** prints a textual representation of the complete contents of each file as described by the format description. This will also validate the entire file against the format description and warn of any discrepancies.

**--query**=*QUERY*  and **--query-file**=*FILE* print the results of applying the specified format query to each file. (We haven't even begun to describe format queries but the idea would be to select only values of specified types that satisfy certain constraints, for example "Ligature where componentCount > 2").

If no output option is specified it defaults to `--summary`.

## Examples
```
fathom FILES...
```
Print a summary of each file after best-effort identification using the installed catalog of format descriptions.

```
fathom --format opentype --dump *.otf
```
Print a complete dump of each file interpreted as an OpenType font.

**Comment by toothbrush** [comment]
Question for the audience: what should the REPL look like / how should it behave / how should it be invoked?

**Comment by mikeday** [comment]
Do we _need_ a REPL? Seems like we could skip it for now.

**Comment by brendanzab** [comment]
I just have it as  a subcommand in Pikelet, ie. `pikelet repl`. Could be handy for quickly checking things? It's not too difficult to implement a rudimentary one. Here's how I do it in Pikelet: https://github.com/pikelet-lang/pikelet/blob/next/pikelet-cli/src/repl.rs

**Comment by brendanzab** [comment]
I was considering switching to `pikelet interactive` though, in my quest to remove confusing acronyms 😅

**Comment by brendanzab** [comment]
I'd imagine that eventually you might be able to encode and decode formats from this mode, and maybe step through how data is decoded interactively? But that's more thinking long term.

**Comment by toothbrush** [comment]
> I'd imagine that eventually you might be able to encode and decode formats from this mode, and maybe step through how data is decoded interactively? But that's more thinking long term.

Yeah, i'd want to avoid complicating v1.  But it does sound cool :)

Probably i'll either make it very rudimentary (e.g., copy-pasta from Pikelet) or just avoid for now.
