### ISSUE TITLE
Dependent struct formats and struct types

### ISSUE THREAD

**Issue by brendanzab** [yeslogic/fathom#244]
This will allow dependent struct formats to have field dependencies, which correspond to how structs are parsed in a binary format. For example:

```
struct Points : Format {
    len : U32Be,
    data : FormatArray len { x : U32Be, y U32Be },
}
```

Note that `len` is bound as `len : Repr U32Be` in the typing context. 

Unlike DDC we aim to preserve as much dependency information in the host language as possible. To that end `Repr` will interpret dependent struct formats into dependent struct types (as opposed to a non-dependent structs). 

We need to be careful of maintaining dependencies when looking up fields in these records. For example:

```
struct MyArray {
    len : Int,
    data : Array len Point,
}

get_data (array : MyArray) =
    array.data; // type of body is `Array array.len Point`
```

This will require us to implement local environments. When doing so we'll also have to update the `Bool` and `Int` eliminators to capture their current environment (lest we introduce weird scoping behaviour!)

**Comment by toothbrush** [comment]
Here's a note: https://github.com/yeslogic/fathom/pull/248/commits/ec7e6829e80eb12d2b4cd8500fae4e35f433cf44#r508133011
