### ISSUE TITLE
Create top-level compiler API

### ISSUE THREAD

**Issue by toothbrush** [yeslogic/fathom#261]
Currently the test suite reaches into compiler internals.  We should extract that, to unblock creating a CLI.  The test suite & CLI can then use that API.

**Comment by brendanzab** [comment]
There might be more interesting ones, but here's some stuff that I know of:

- https://github.com/SomewhatML/sml-compiler/tree/master/crates/sml-driver
- https://github.com/lalrpop/lalrpop/blob/master/lalrpop/src/api/mod.rs
- https://github.com/ollef/sixty/blob/master/src/Driver.hs
- https://github.com/rust-lang/rust/tree/master/compiler/rustc_driver
- https://github.com/MLton/mlton/tree/master/mlton/main
- https://github.com/edwinb/Idris2/blob/master/src/Idris/Driver.idr
