### ISSUE TITLE
Add hints to `Const`s to improve the distillation of integer constants

### ISSUE THREAD

**Issue by brendanzab** [yeslogic/fathom#328]
Currently the distiller has know way of knowing how to render constants, instead just defaulting to rendering as decimal numbers. We could fix this by altering `Const` to be:

```rs
enum IntStyle {
    Binary,
    Decimal,
    Hexadecimal,
    Ascii,
}

pub enum Const {
    U8(u8, IntStyle),
    U16(u16, IntStyle),
    U32(u32, IntStyle),
    U64(u64, IntStyle),
    S8(i8, IntStyle),
    S16(i16, IntStyle),
    S32(i32, IntStyle),
    S64(i64, IntStyle),
    // TODO: use logical equality for floating point numbers
    F32(f32),
    F64(f64),
    Pos(u64),
    Ref(u64),
}
```

This will allow us to convert back to an appropriate literal (either numeric or string) during distillation.

One thing we'll need to consider is to ignore the style hint when comparing constants for equality. We could do this by a custom overload `PartialEq`, or, by implementing our own method (eg. `Const::logical_eq`), which will involve updates to `surface::elaboration::unification` and `core::semantics`:

- https://github.com/yeslogic/fathom/blob/76414023a3e7298be1b1386c23a37e77b80135de/fathom/src/core/semantics.rs#L948
- https://github.com/yeslogic/fathom/blob/76414023a3e7298be1b1386c23a37e77b80135de/fathom/src/surface/elaboration/unification.rs#L280

Another complication is how to handle the style hints in the primitive/builtin ops - we'll need to ignore or merge them somehow to figure out what to use in the returned constant.

**Comment by brendanzab** [comment]
Adding a custom equality comparison will be handy at any rate - will need to eventually looking at fixing that TODO about float comparisons 😅

**Comment by brendanzab** [comment]
Oh, I should add that I used to implement a similar thing in v2:

https://github.com/yeslogic/fathom/blob/168a5f922ec376ba221817b951977e9cb001143e/experiments/rust-prototype-v2/src/syntax/mod.rs#L35-L41

**Comment by mikeday** [comment]
This would not help us dump struct fields with a specific style, would it?

**Comment by brendanzab** [comment]
OHH! You are indeed right! 🤦‍♂️

This only helps for preserving the style of constants in the original format through elaboration, and back via distillation to pretty printing. Rendering parsed formats in specific styles would be a separate issue.

**Comment by mikeday** [comment]
Are consts and other terms associated with a codespan for error reporting purposes?

**Comment by wezm** [comment]
> Are consts and other terms associated with a codespan for error reporting purposes?

`Term` carries a range that used when producing diagnostics: https://github.com/yeslogic/fathom/blob/76414023a3e7298be1b1386c23a37e77b80135de/fathom/src/surface.rs#L55

**Comment by mikeday** [comment]
The fact that a const was a particular type of literal in the original source feels related to this range I feel :thinking:

**Comment by brendanzab** [comment]
> Are consts and other terms associated with a codespan for error reporting purposes?

In the surface language yes, but this info is currently lost once we get into the core language. We'll most likely need to add it to the core language at some stage.
