### ISSUE TITLE
Sugar for multi parameter functions

### ISSUE THREAD

**Issue by brendanzab** [yeslogic/fathom#335]
At the moment the syntax for multiple parameter function types and function literals is a bit tiresome:

```
fun (a : A) -> fun (b : B a) -> C a b
fun (a : A) => fun (b : B) => c a b
```

It would be nice to be able to write the following:

```
fun (a : A) (b : B a) -> C a b
fun (a : A) (b : B a) => c a b
```

To do this we would update the AST of the surface language to allow multiple parameters, elaborating to single-parameter functions in the core language.

**Comment by Kmeakin** [comment]
I think this should have been closed by https://github.com/yeslogic/fathom/pull/400?

**Comment by brendanzab** [comment]
Oh yes, you are right!
