### ISSUE TITLE
Inconsistency between synthesised function literals and checked function literals

### ISSUE THREAD

**Issue by Kmeakin** [yeslogic/fathom#408]
The behaviour of function literals changes depending on whether they are synthesised or checked during elaboration.

eg:
`fun (A : Type) (B : Type) (p : {x : A, y : B}) => p.x`
elaborates to `fun A B p => p.a : fun (A : Type) (B : Type) -> { a : A, b : B } -> A`

but
`(fun (A : Type) (B : Type) (p : {x : A, y : B}) => p.x) : _`
elaborates to `fun A B p => p.a : fun (A : Type) -> Type -> { a : A, b : a } -> A`

**Comment by brendanzab** [comment]
Oh, nice catch, thanks! 🙏
